CREATE TABLE Restaurants (
id INT AUTO_INCREMENT,
name VARCHAR(200) NOT NULL,
address VARCHAR(500) NOT NULL,
visitedDate DATE NOT NULL,
webURL VARCHAR(500),
yelpURL VARCHAR(500),
cuisineId SMALLINT NOT NULL,
ourRating INT NOT NULL,
expense  VARCHAR(4),
amtPaid DECIMAL(5,2) NOT NULL,
isClosed BOOLEAN NOT NULL DEFAULT FALSE,
versionStartDate DATE NOT NULL,
versionEndDate DATE,
venueId SMALLINT NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(cuisineId) REFERENCES Cuisine(id),
FOREIGN KEY(venueId) REFERENCES Venue(venueId)
);